version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty77
      - POSTGRES_DB=restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    image: maxkemzi/restaurant:latest
    environment:
      - DB_URL=postgresql://postgres:qwerty77@postgres:5432/restaurant?schema=public
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "3000:3000"
volumes:
  postgres:
