name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Setup database
        run: npx prisma migrate deploy
      - name: Run tests
        run: npm test -- --reporter=html --outputFile=./reports/tests/index.html
      - name: Check code style
        run: npm run lint -- -f node_modules/eslint-html-reporter/reporter.js -o ./reports/lint/index.html
      - name: Upload lint and test results
        uses: actions/upload-artifact@v3
      with:
        name: ci-results
        path: ./reports/
  deploy:
    runs-on: ubuntu-latest
    needs: pipeline
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}